with open("Poem_output.txt", "w") as file:
    file.write("A poem of life\n")
    file.write("----------------\n")
    file.write("A man dies and decays in his grave\n")
    file.write("leaving behind all his achievements and wealth\n")
    file.write("None will remember him for all that, but only with them how he behaved\n")
    file.write("Everyone will remember him based on with him, how they felt\n.")
    file.write("----------------\n")
    file.write("In a graveyard, none will think\n")
    file.write("whether the deceased lived in a brick kiln\n")
    file.write("or in mansions made of gold")
    file.write("but among the masses, the story of the deceased's character will be told.\n")
    file.write("----------------")
    file.write("Purpose gives man's life meaning\n")
    file.write("One who even though doesn't have the most of wealth but has fulfilled his true purpose lawfully\n")
    file.write("is a true human being.\n")
    file.write("If he made his life belong to noble character\n")
    file.write("Everyone will cherish his name eternally\n")
    file.write("But if man has high wealth but lives his life as a clown\n")
    file.write("after his death, upon him everyone will frown.\n")
